# Terminal setup
# set -g default-terminal 'tmux-256color'
set -g default-terminal 'xterm-ghostty'
set -as terminal-overrides ",xterm-ghostty*:Tc"

# Status and mouse
set-option -g status-position top
set -g mouse on

# Prefix key
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Tmux tmux-sessionizer
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

# Vim-style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize the current pane using Alt + direction
bind -n M-k resize-pane -U 5
bind -n M-j resize-pane -D 5
bind -n M-h resize-pane -L 5
bind -n M-l resize-pane -R 5

# Start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Alt-arrow keys to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrows to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift+Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# ================= TPM Plugins =================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

# Load TPM.
run '~/.tmux/plugins/tpm/tpm'
# ===============================================


# ===========Custom status line theme============
# Catppuccin Mocha palette:
#   Mantle   #181825  base bg
#   Surface0 #313244  inactive window bg
#   Green    #a6e3a1  session name accent
#   Mauve    #cba6f7  current window accent
#   Subtext0 #a6adc8  dimmed text
#   Text     #cdd6f4  main text

set -g status-style "bg=#181825,fg=#cdd6f4"
set -g status-justify left
set -g status-left-length 100

# Session name — Green box
set -g status-left "#[bg=blue,fg=#1e1e2e,bold] #S #[bg=#313244,fg=#a6e3a1]"
set -g status-right ""

# Inactive windows — Surface0 bg, Subtext0 text
set -g window-status-format "#[fg=#a6adc8,bg=#313244] ○ #I·#W "
set -g window-status-current-format "#[fg=#1e1e2e,bold,bg=#cba6f7] ● #I·#W "

# No separator
set -g window-status-separator ""

# Pane border style
set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#cba6f7"
# ===============================================

# vi-mode
set-window-option -g mode-keys vi

# Copy mode keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Split windows with current path
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Popup keybindings
bind-key G display-popup -w 80% -h 80% -E "lazygit"
bind-key C display-popup -w 80% -h 80% -E "claude"
